// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PinkRooster.Data;

#nullable disable

namespace PinkRooster.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311211027_AddMissingFkAndDependencyIndexes")]
    partial class AddMissingFkAndDependencyIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PinkRooster.Data.Entities.AcceptanceCriterion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("PhaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("phase_id");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("verification_method");

                    b.Property<string>("VerificationResult")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("verification_result");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("acceptance_criteria", (string)null);
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.ActivityLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CallerIdentity")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("caller_identity");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("http_method");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("path");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CallerIdentity");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.FeatureRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AcceptanceSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("acceptance_summary");

                    b.Property<string>("BusinessValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("business_value");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<int>("FeatureRequestNumber")
                        .HasColumnType("integer")
                        .HasColumnName("feature_request_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Requester")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requester");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Priority");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("ProjectId", "FeatureRequestNumber")
                        .IsUnique();

                    b.ToTable("feature_requests", (string)null);
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.FeatureRequestAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by");

                    b.Property<long>("FeatureRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("feature_request_id");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("old_value");

                    b.HasKey("Id");

                    b.HasIndex("FeatureRequestId");

                    b.ToTable("feature_request_audit_logs", (string)null);
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.Issue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualBehavior")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("actual_behavior");

                    b.Property<string>("AffectedComponent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("affected_component");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("ExpectedBehavior")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("expected_behavior");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("integer")
                        .HasColumnName("issue_number");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("issue_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("Resolution")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("RootCause")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("root_cause");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("stack_trace");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<string>("StepsToReproduce")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("steps_to_reproduce");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Priority");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Severity");

                    b.HasIndex("State");

                    b.HasIndex("ProjectId", "IssueNumber")
                        .IsUnique();

                    b.ToTable("issues", (string)null);
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.IssueAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_name");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("issue_id");

                    b.Property<string>("NewValue")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("old_value");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("issue_audit_logs", (string)null);
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.PhaseAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("old_value");

                    b.Property<long>("PhaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("phase_id");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("phase_audit_logs", (string)null);
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProjectPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("project_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ProjectPath")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.TaskAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("old_value");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("task_audit_logs", (string)null);
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.WorkPackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<int?>("EstimatedComplexity")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_complexity");

                    b.Property<string>("EstimationRationale")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("estimation_rationale");

                    b.Property<long?>("LinkedFeatureRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("linked_feature_request_id");

                    b.Property<long?>("LinkedIssueId")
                        .HasColumnType("bigint")
                        .HasColumnName("linked_issue_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Plan")
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)")
                        .HasColumnName("plan");

                    b.Property<string>("PreviousActiveState")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("previous_active_state");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("WorkPackageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("work_package_number");

                    b.HasKey("Id");

                    b.HasIndex("LinkedFeatureRequestId");

                    b.HasIndex("LinkedIssueId");

                    b.HasIndex("Priority");

                    b.HasIndex("ProjectId");

                    b.HasIndex("State");

                    b.HasIndex("Type");

                    b.HasIndex("ProjectId", "WorkPackageNumber")
                        .IsUnique();

                    b.ToTable("work_packages", (string)null);
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.WorkPackageAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("old_value");

                    b.Property<long>("WorkPackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_package_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkPackageId");

                    b.ToTable("work_package_audit_logs", (string)null);
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.WorkPackageDependency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DependentWorkPackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("dependent_work_package_id");

                    b.Property<long>("DependsOnWorkPackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("depends_on_work_package_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnWorkPackageId");

                    b.HasIndex("DependentWorkPackageId", "DependsOnWorkPackageId")
                        .IsUnique();

                    b.ToTable("work_package_dependencies", (string)null);
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.WorkPackagePhase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PhaseNumber")
                        .HasColumnType("integer")
                        .HasColumnName("phase_number");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("WorkPackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_package_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkPackageId");

                    b.HasIndex("WorkPackageId", "PhaseNumber")
                        .IsUnique();

                    b.ToTable("work_package_phases", (string)null);
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.WorkPackageTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<string>("ImplementationNotes")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("implementation_notes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long>("PhaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("phase_id");

                    b.Property<string>("PreviousActiveState")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("previous_active_state");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<int>("TaskNumber")
                        .HasColumnType("integer")
                        .HasColumnName("task_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("WorkPackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("work_package_id");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.HasIndex("State");

                    b.HasIndex("WorkPackageId");

                    b.HasIndex("WorkPackageId", "TaskNumber")
                        .IsUnique();

                    b.ToTable("work_package_tasks", (string)null);
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.WorkPackageTaskDependency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DependentTaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("dependent_task_id");

                    b.Property<long>("DependsOnTaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("depends_on_task_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnTaskId");

                    b.HasIndex("DependentTaskId", "DependsOnTaskId")
                        .IsUnique();

                    b.ToTable("work_package_task_dependencies", (string)null);
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.AcceptanceCriterion", b =>
                {
                    b.HasOne("PinkRooster.Data.Entities.WorkPackagePhase", "Phase")
                        .WithMany("AcceptanceCriteria")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.FeatureRequest", b =>
                {
                    b.HasOne("PinkRooster.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("PinkRooster.Data.Entities.FileReference", "Attachments", b1 =>
                        {
                            b1.Property<long>("FeatureRequestId")
                                .HasColumnType("bigint");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("RelativePath")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FeatureRequestId", "__synthesizedOrdinal");

                            b1.ToTable("feature_requests");

                            b1
                                .ToJson("attachments")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("FeatureRequestId");
                        });

                    b.OwnsMany("PinkRooster.Data.Entities.UserStory", "UserStories", b1 =>
                        {
                            b1.Property<long>("FeatureRequestId")
                                .HasColumnType("bigint");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Benefit")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Goal")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FeatureRequestId", "__synthesizedOrdinal");

                            b1.ToTable("feature_requests");

                            b1
                                .ToJson("user_stories")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("FeatureRequestId");
                        });

                    b.Navigation("Attachments");

                    b.Navigation("Project");

                    b.Navigation("UserStories");
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.FeatureRequestAuditLog", b =>
                {
                    b.HasOne("PinkRooster.Data.Entities.FeatureRequest", "FeatureRequest")
                        .WithMany()
                        .HasForeignKey("FeatureRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureRequest");
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.Issue", b =>
                {
                    b.HasOne("PinkRooster.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("PinkRooster.Data.Entities.FileReference", "Attachments", b1 =>
                        {
                            b1.Property<long>("IssueId")
                                .HasColumnType("bigint");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("RelativePath")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IssueId", "__synthesizedOrdinal");

                            b1.ToTable("issues");

                            b1
                                .ToJson("attachments")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("IssueId");
                        });

                    b.Navigation("Attachments");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.IssueAuditLog", b =>
                {
                    b.HasOne("PinkRooster.Data.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.PhaseAuditLog", b =>
                {
                    b.HasOne("PinkRooster.Data.Entities.WorkPackagePhase", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.TaskAuditLog", b =>
                {
                    b.HasOne("PinkRooster.Data.Entities.WorkPackageTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.WorkPackage", b =>
                {
                    b.HasOne("PinkRooster.Data.Entities.FeatureRequest", "LinkedFeatureRequest")
                        .WithMany()
                        .HasForeignKey("LinkedFeatureRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PinkRooster.Data.Entities.Issue", "LinkedIssue")
                        .WithMany()
                        .HasForeignKey("LinkedIssueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PinkRooster.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("PinkRooster.Data.Entities.FileReference", "Attachments", b1 =>
                        {
                            b1.Property<long>("WorkPackageId")
                                .HasColumnType("bigint");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("RelativePath")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WorkPackageId", "__synthesizedOrdinal");

                            b1.ToTable("work_packages");

                            b1
                                .ToJson("attachments")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkPackageId");
                        });

                    b.Navigation("Attachments");

                    b.Navigation("LinkedFeatureRequest");

                    b.Navigation("LinkedIssue");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.WorkPackageAuditLog", b =>
                {
                    b.HasOne("PinkRooster.Data.Entities.WorkPackage", "WorkPackage")
                        .WithMany()
                        .HasForeignKey("WorkPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkPackage");
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.WorkPackageDependency", b =>
                {
                    b.HasOne("PinkRooster.Data.Entities.WorkPackage", "DependentWorkPackage")
                        .WithMany("BlockedBy")
                        .HasForeignKey("DependentWorkPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PinkRooster.Data.Entities.WorkPackage", "DependsOnWorkPackage")
                        .WithMany("Blocking")
                        .HasForeignKey("DependsOnWorkPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependentWorkPackage");

                    b.Navigation("DependsOnWorkPackage");
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.WorkPackagePhase", b =>
                {
                    b.HasOne("PinkRooster.Data.Entities.WorkPackage", "WorkPackage")
                        .WithMany("Phases")
                        .HasForeignKey("WorkPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkPackage");
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.WorkPackageTask", b =>
                {
                    b.HasOne("PinkRooster.Data.Entities.WorkPackagePhase", "Phase")
                        .WithMany("Tasks")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PinkRooster.Data.Entities.WorkPackage", "WorkPackage")
                        .WithMany()
                        .HasForeignKey("WorkPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("PinkRooster.Data.Entities.FileReference", "Attachments", b1 =>
                        {
                            b1.Property<long>("WorkPackageTaskId")
                                .HasColumnType("bigint");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("RelativePath")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WorkPackageTaskId", "__synthesizedOrdinal");

                            b1.ToTable("work_package_tasks");

                            b1
                                .ToJson("attachments")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkPackageTaskId");
                        });

                    b.OwnsMany("PinkRooster.Data.Entities.FileReference", "TargetFiles", b1 =>
                        {
                            b1.Property<long>("WorkPackageTaskId")
                                .HasColumnType("bigint");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("RelativePath")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WorkPackageTaskId", "__synthesizedOrdinal");

                            b1.ToTable("work_package_tasks");

                            b1
                                .ToJson("target_files")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkPackageTaskId");
                        });

                    b.Navigation("Attachments");

                    b.Navigation("Phase");

                    b.Navigation("TargetFiles");

                    b.Navigation("WorkPackage");
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.WorkPackageTaskDependency", b =>
                {
                    b.HasOne("PinkRooster.Data.Entities.WorkPackageTask", "DependentTask")
                        .WithMany("BlockedBy")
                        .HasForeignKey("DependentTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PinkRooster.Data.Entities.WorkPackageTask", "DependsOnTask")
                        .WithMany("Blocking")
                        .HasForeignKey("DependsOnTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependentTask");

                    b.Navigation("DependsOnTask");
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.WorkPackage", b =>
                {
                    b.Navigation("BlockedBy");

                    b.Navigation("Blocking");

                    b.Navigation("Phases");
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.WorkPackagePhase", b =>
                {
                    b.Navigation("AcceptanceCriteria");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PinkRooster.Data.Entities.WorkPackageTask", b =>
                {
                    b.Navigation("BlockedBy");

                    b.Navigation("Blocking");
                });
#pragma warning restore 612, 618
        }
    }
}
